name: Windows CI
on: [push, pull_request]

jobs:
  win10-clang:
    runs-on: windows-2019
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install build tools
        run: choco install meson --version 1.0.1 -y --ignorepackagecodes
      - name: Setup build environment
        run: meson build
      - name: Compile project
        run: cd .\build\ && ninja -j4
      - uses: actions/upload-artifact@v3
        with:
          name: mpdscribble-windows-amd64.exe
          path: mpdscribble.exe